import type { CaseStudy, Service, Testimonial, Project, HeroContent, Profile } from './types'

export const siteConfig = {
  name: 'Rifat Ahmed',
  title: 'AI Automation Consultant',
  description: 'I build AI systems and automation workflows that eliminate bottlenecks, reduce manual work, and unlock growth for ambitious businesses.',
  url: 'https://rifatahmed.dev',
  ogImage: '/og.png',
  email: 'hello@rifatahmed.dev',
  calendly: 'https://calendly.com/rifatahmed',
}

export const heroContent: HeroContent = {
  id: '1',
  headline: 'AI Systems That Save Time,\nReduce Costs &\nScale Operations.',
  subheadline: 'AI Automation Consultant & Builder',
  description: 'I build custom AI agents, workflow automations, CRM integrations and internal tools that eliminate repetitive work and help businesses operate faster.',
  cta_primary_text: 'Book A Discovery Call',
  cta_primary_href: '/contact',
  cta_secondary_text: 'View Case Studies',
  cta_secondary_href: '/case-studies',
  stat_1_value: '25+',
  stat_1_label: 'Automations Delivered',
  stat_2_value: '1,000+',
  stat_2_label: 'Hours Saved',
  stat_3_value: '15+',
  stat_3_label: 'Businesses Helped',
  stat_4_value: '80%',
  stat_4_label: 'Response Time Improvement',
  updated_at: new Date().toISOString(),
}

export const profile: Profile = {
  id: '1',
  name: 'Rifat Ahmed',
  title: 'AI Automation Consultant & Builder',
  bio: 'I help businesses move faster by replacing manual, repetitive work with intelligent automation systems built on AI agents, n8n, and custom tooling.',
  avatar_url: null,
  location: 'Remote · Worldwide',
  email: 'hello@rifatahmed.dev',
  phone: null,
  availability: 'Available for new projects',
  years_experience: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const services: Service[] = [
  {
    id: '1',
    title: 'AI Agents',
    description: 'Deploy AI that works around the clock — qualifying leads, responding to inquiries, and completing complex multi-step tasks without anyone lifting a finger.',
    icon: 'Bot',
    features: ['Multi-step reasoning', 'Tool use & API calls', 'Memory & context', 'Human-in-the-loop escalation'],
    sort_order: 1,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Workflow Automation',
    description: 'Connect every tool in your stack with trigger-based workflows that act instantly — eliminating manual handoffs and freeing your team from repetitive operational work.',
    icon: 'Workflow',
    features: ['400+ integrations', 'Custom logic nodes', 'Error handling & retries', 'Self-hosted or cloud'],
    sort_order: 2,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'CRM Integrations',
    description: 'Every lead, deal, and customer interaction synced in real time across HubSpot, Salesforce, or Pipedrive — so your team always has the full picture without data entry.',
    icon: 'Users',
    features: ['HubSpot, Salesforce, Pipedrive', 'Bi-directional sync', 'Custom field mapping', 'Event-driven triggers'],
    sort_order: 3,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Internal Business Tools',
    description: 'Replace scattered spreadsheets and one-off workarounds with purpose-built tools that give your entire team structure, shared visibility, and a single source of truth.',
    icon: 'Layers',
    features: ['Role-based access', 'Custom workflows', 'Data pipelines', 'API integrations'],
    sort_order: 4,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Dashboard Development',
    description: 'Pull data from every corner of your business into clean, real-time dashboards that give leadership instant visibility into performance, pipeline, and bottlenecks.',
    icon: 'BarChart3',
    features: ['Real-time data', 'Custom visualizations', 'Multi-source aggregation', 'Shareable reports'],
    sort_order: 5,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Lead Generation Systems',
    description: 'Automated pipelines that find, enrich, and qualify prospects 24/7 — delivering sales-ready leads directly into your CRM while your team stays focused on closing.',
    icon: 'Target',
    features: ['Multi-channel sourcing', 'AI enrichment', 'Intent scoring', 'Automated outreach'],
    sort_order: 6,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const caseStudies: CaseStudy[] = [
  {
    id: '1',
    project_id: null,
    title: 'AI Sales Agent Closes 3× More Deals for SaaS Company',
    slug: 'saas-ai-sales-agent',
    client_name: 'Confidential SaaS Co.',
    client_industry: 'B2B SaaS',
    client_size: '50–200 employees',
    challenge: 'The sales team was spending 4–6 hours daily on manual prospect research, follow-up emails, and CRM updates — leaving almost no time for actual selling. Pipeline visibility was poor and deals were slipping through the cracks.',
    solution: 'Built an AI sales agent using Claude + n8n that automatically researches inbound leads, scores them against ICP, drafts personalized outreach, and handles follow-up sequences — all synced in real time to HubSpot.',
    implementation: 'Deployed in 3 phases over 6 weeks: Phase 1 was lead enrichment and scoring, Phase 2 was automated outreach drafts with human review, Phase 3 was full autonomous follow-up with escalation triggers.',
    results: 'Sales team reclaimed 25+ hours per week. Qualified pipeline grew by 312% in 90 days. Deal velocity improved by 2.4×. Close rate increased from 18% to 31%.',
    testimonial_quote: 'Rifat built something I didn\'t think was possible — an AI that actually understands our ICP and writes emails that get replies. Our team loves it.',
    testimonial_author: 'Head of Sales',
    testimonial_role: 'Head of Sales',
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['AI Agents', 'n8n', 'HubSpot', 'Sales Automation'],
    tech_stack: ['Claude API', 'n8n', 'HubSpot', 'OpenAI', 'PostgreSQL'],
    duration: '6 weeks',
    metrics: [
      { value: '312%', label: 'Pipeline Growth', description: 'In first 90 days' },
      { value: '25h+', label: 'Weekly Time Saved', description: 'Per sales rep' },
      { value: '3×', label: 'Close Rate Improvement', description: '18% → 31%' },
    ],
    featured: false,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    project_id: null,
    title: 'Automated Invoice Processing Saves 40 Hours Weekly at Logistics Firm',
    slug: 'logistics-invoice-automation',
    client_name: 'Regional Logistics Co.',
    client_industry: 'Logistics & Supply Chain',
    client_size: '100–500 employees',
    challenge: 'Finance team manually processed 800+ invoices weekly across 40+ vendors — reconciling against POs, flagging discrepancies, and updating the ERP. Error rate was 4.2% and the process required 3 full-time staff.',
    solution: 'Built an intelligent document processing pipeline using OCR, Claude for extraction and validation, n8n for orchestration, and direct ERP API integration for automated posting.',
    implementation: null,
    results: 'Invoice processing time reduced from 45 minutes to under 2 minutes per invoice. Error rate dropped to 0.3%. 3 staff redeployed to higher-value work. Annual savings exceed $180,000.',
    testimonial_quote: 'The ROI was obvious within the first month. What used to take my team a full week now runs overnight.',
    testimonial_author: 'CFO',
    testimonial_role: 'CFO',
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['Document AI', 'n8n', 'ERP Integration', 'Finance Automation'],
    tech_stack: ['Claude API', 'n8n', 'OCR', 'REST APIs', 'PostgreSQL'],
    duration: '8 weeks',
    metrics: [
      { value: '96%', label: 'Time Reduction', description: '45 min → 2 min per invoice' },
      { value: '$180K', label: 'Annual Savings', description: 'Fully automated workflow' },
      { value: '0.3%', label: 'Error Rate', description: 'Down from 4.2%' },
    ],
    featured: false,
    sort_order: 5,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    project_id: null,
    title: 'Lead Generation System Delivers 500+ Qualified Leads Monthly for Agency',
    slug: 'agency-lead-generation-system',
    client_name: 'Growth Marketing Agency',
    client_industry: 'Digital Marketing',
    client_size: '10–50 employees',
    challenge: 'Agency relied entirely on referrals and had no systematic outbound. Founders were spending 15+ hours weekly manually finding leads, most of which didn\'t convert because targeting was imprecise.',
    solution: 'Built a multi-channel lead generation system that scrapes, enriches, scores, and sequences prospects from LinkedIn, Apollo, and industry databases — with AI-generated personalization at scale.',
    implementation: null,
    results: '500+ qualified leads per month on autopilot. 22% email open rate (industry average: 21%). 8% reply rate (industry average: 3%). 4 new clients signed in first month.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['Lead Generation', 'AI Personalization', 'n8n', 'LinkedIn'],
    tech_stack: ['n8n', 'Claude API', 'Apollo API', 'LinkedIn', 'Instantly'],
    duration: '4 weeks',
    metrics: [
      { value: '500+', label: 'Leads/Month', description: 'Fully automated pipeline' },
      { value: '8%', label: 'Reply Rate', description: '2.7× industry average' },
      { value: '4', label: 'New Clients', description: 'In first 30 days' },
    ],
    featured: false,
    sort_order: 6,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    project_id: null,
    title: 'Real-Time Operations Dashboard Unifies 7 Data Sources for E-commerce Brand',
    slug: 'ecommerce-operations-dashboard',
    client_name: 'DTC E-commerce Brand',
    client_industry: 'E-commerce',
    client_size: '$5M–$20M ARR',
    challenge: 'Leadership team was making decisions based on day-old reports manually compiled from Shopify, Meta Ads, Google Ads, Klaviyo, Warehouse WMS, and 3PL — a 3-hour daily exercise with no real-time visibility.',
    solution: 'Built a unified operations dashboard with real-time data pipelines from all 7 sources, with automated anomaly detection and Slack alerts for key threshold breaches.',
    implementation: null,
    results: 'Decision latency reduced from 24 hours to 5 minutes. Ad spend optimization improved ROAS by 34% in 60 days. Daily report preparation eliminated (saving 15 hours/week for ops team).',
    testimonial_quote: 'This dashboard is the single source of truth for our entire operation. We caught a fulfillment issue in 10 minutes that would have cost us $50K.',
    testimonial_author: 'COO',
    testimonial_role: 'COO',
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['Dashboard', 'Data Integration', 'n8n', 'Real-Time Analytics'],
    tech_stack: ['Next.js', 'Supabase', 'n8n', 'Shopify API', 'Meta API'],
    duration: '5 weeks',
    metrics: [
      { value: '34%', label: 'ROAS Improvement', description: 'Within 60 days' },
      { value: '15h', label: 'Saved Weekly', description: 'Report automation' },
      { value: '5 min', label: 'Decision Latency', description: 'Down from 24 hours' },
    ],
    featured: false,
    sort_order: 7,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    project_id: null,
    title: 'AI Lead Response System Cuts Real Estate Reply Time from Hours to 30 Seconds',
    slug: 'real-estate-lead-response',
    client_name: 'Real Estate Agency',
    client_industry: 'Real Estate',
    client_size: 'Small agency',
    challenge: 'A growing real estate agency was losing qualified buyers due to slow response times. New inquiries sat unanswered for hours, leads arriving outside business hours went completely unaddressed, and agents spent significant time writing repetitive follow-up emails — resulting in lost opportunities before any real conversation began.',
    solution: 'Built an AI-powered Lead Response System that instantly captures buyer inquiries, generates personalized email responses within 30 seconds using AI, assigns a lead quality score, logs every submission to a centralized database, and automatically runs a multi-step nurture sequence on Day 2, Day 5, and Day 7.',
    implementation: 'Deployed in 3 phases over 1 week: Phase 1 — AI response generation with a 30-second reply SLA. Phase 2 — Lead scoring and qualification logic to surface high-intent buyers. Phase 3 — Automated multi-step follow-up sequences operating 24/7, including weekends and holidays.',
    results: 'Every inquiry now receives a personalized AI response within 30 seconds, including evenings and weekends. Agents were freed from writing repetitive replies. Lead data centralized in a searchable database. Zero missed inquiries outside business hours. Buyer engagement improved across the entire funnel.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image.png',
    pdf_url: 'https://res.cloudinary.com/dsyhgdfvc/raw/upload/v1781801999/portfolio/pdfs/real-estate-lead-response.pdf',
    live_url: null,
    tags: ['AI Agents', 'Real Estate', 'Lead Automation', 'Email Automation'],
    tech_stack: ['n8n', 'Claude API', 'Email Automation', 'Google Sheets', 'Lead Scoring'],
    duration: '1 week',
    metrics: [
      { value: '30s', label: 'Response Time', description: 'Down from hours of delay' },
      { value: '24/7', label: 'Availability', description: 'Including evenings & weekends' },
      { value: '3-Step', label: 'Follow-Up Sequence', description: 'Day 2, Day 5, Day 7' },
    ],
    content_blocks: [
      { type: 'lead', text: 'In real estate, speed wins. An AI-powered lead engagement system that responds to every property inquiry in under 30 seconds, qualifies prospects, automates follow-up, and ensures no opportunity is ever lost to a slow reply.' },

      { type: 'heading', level: 2, text: 'The Problem' },
      { type: 'paragraph', text: 'When a prospective buyer submits an inquiry, they\'re often evaluating multiple properties and contacting several agents at once. Every minute of delay narrows the window of opportunity.' },
      { type: 'list', items: [
        'New inquiries sit unanswered for hours',
        'Leads arrive outside business hours',
        'Agents spend valuable time on repetitive replies',
        'Follow-ups are inconsistent or forgotten',
        'Buyers lose interest before real engagement begins',
      ] },

      { type: 'heading', level: 2, text: 'The Objective' },
      { type: 'list', style: 'check', items: [
        'Respond to inquiries within seconds',
        'Personalize communication based on buyer details',
        'Identify high-value prospects',
        'Automate follow-up sequences',
        'Centralize the lead database',
        'Ensure no inquiry goes unanswered',
      ] },

      { type: 'heading', level: 2, text: 'The Solution' },
      { type: 'paragraph', text: 'An AI-powered Lead Response System that captures buyer inquiries, generates personalized email responses, scores lead quality, and nurtures prospects through a multi-step follow-up sequence — so agents only spend time on conversations that matter.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_1.png', caption: 'High-level system architecture' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_2.png', caption: 'AI response generation flow' },

      { type: 'heading', level: 2, text: 'Workflow Overview' },

      { type: 'heading', level: 3, text: 'Step 1 — Buyer Submits Inquiry' },
      { type: 'paragraph', text: 'A buyer completes an inquiry form capturing name, email, preferred location, property type, and budget. The submission is instantly processed by the workflow.' },

      { type: 'heading', level: 3, text: 'Step 2 — AI Generates a Personalized Response' },
      { type: 'paragraph', text: 'The system analyzes the buyer\'s details and produces a custom response that acknowledges their interest and references their specific requirements — delivered within ~30 seconds.' },

      { type: 'heading', level: 3, text: 'Step 3 — Lead Qualification' },
      { type: 'paragraph', text: 'Each inquiry is evaluated and assigned a lead score based on engagement and buying intent, so agents know who deserves immediate attention.' },

      { type: 'heading', level: 3, text: 'Step 4 — Automatic Lead Logging' },
      { type: 'paragraph', text: 'Every submission flows into a centralized database with buyer details, property preferences, budget, lead score, status, and timestamp — eliminating manual data entry.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_3.png', caption: 'Centralized lead database' },

      { type: 'heading', level: 3, text: 'Step 5 — Automated Follow-Up Sequence' },
      { type: 'paragraph', text: 'Most leads don\'t convert on the first interaction. The system runs a 3-step nurture sequence:' },
      { type: 'list', items: [
        'Day 2 — Re-engagement message',
        'Day 5 — Value-driven check-in offering further property assistance',
        'Day 7 — Final follow-up encouraging continued discussion',
      ] },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_4.png', caption: 'Multi-step follow-up logic' },

      { type: 'heading', level: 3, text: 'Step 6 — 24/7 Lead Engagement' },
      { type: 'paragraph', text: 'Whether an inquiry arrives during office hours, late at night, or on weekends, every prospect enters the workflow immediately. No lead is left waiting.' },

      { type: 'heading', level: 2, text: 'Key Capabilities' },
      { type: 'list', style: 'check', items: [
        'Instant, personalized lead response within seconds',
        'AI-powered personalization tailored to each buyer',
        'Lead scoring to surface high-priority prospects',
        'Automated lead tracking in a centralized database',
        'Multi-step follow-up automation',
        'Always-on availability — 24/7/365',
      ] },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_5.png', caption: 'Lead scoring view' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_6.png', caption: 'Automated lead tracking' },

      { type: 'heading', level: 2, text: 'Business Impact' },
      { type: 'beforeAfter', before: [
        'Delayed responses to new inquiries',
        'Manual email drafting',
        'Inconsistent follow-up',
        'Lost opportunities outside office hours',
        'Lead info scattered across systems',
      ], after: [
        'Immediate engagement for every inquiry',
        'Consistent communication at scale',
        'Automated lead nurturing',
        'Centralized lead visibility',
        'More agent time on high-value sales activities',
      ] },

      { type: 'heading', level: 2, text: 'Project Gallery' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_7.png', caption: 'Inquiry form experience' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_8.png', caption: 'AI-generated response email' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_9.png', caption: 'Automated workflow architecture' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-response/image_10.png', caption: 'Lead database' },

      { type: 'heading', level: 2, text: 'Outcome' },
      { type: 'paragraph', text: 'By combining instant AI responses, lead qualification, automated nurturing, and centralized tracking, the system ensures every inquiry receives attention while reducing the operational burden on agents — turning interest into conversations and conversations into clients.' },
    ],
    featured: false,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    project_id: null,
    title: 'AI Lead Qualification System Surfaces High-Intent Buyers Instantly for Real Estate Agency',
    slug: 'real-estate-lead-qualification',
    client_name: 'Real Estate Agency',
    client_industry: 'Real Estate',
    client_size: 'Small–mid agency',
    challenge: 'Agents were receiving a constant stream of inquiries from websites, landing pages, and property portals but had no system to separate serious buyers from tire-kickers. Hours were wasted manually reviewing low-intent leads while high-value prospects waited in a crowded inbox — creating a reactive, inefficient sales process.',
    solution: 'Built an AI-driven Lead Qualification System using Groq AI that evaluates each inquiry against buying urgency, budget clarity, and purchase readiness. Each lead is scored 1–10 and routed into Hot / High Priority / Nurture / Low Intent categories. Instant email alerts fire for Hot and High Priority leads with AI-generated summaries and recommended next actions.',
    implementation: 'Single automated pipeline: inquiry submission → Groq AI evaluation (buying intent, budget, urgency, message quality) → score assignment (1–10) → category routing → instant email alert for top leads → auto-log to Google Sheets. Hot leads (9–10) trigger an agent notification within 60 seconds.',
    results: 'Every lead automatically scored within seconds of submission. High-intent buyers now surface to agents immediately. Centralized Google Sheets database eliminated manual data entry. Agents focus 100% of follow-up energy on leads most likely to close. No more missed hot prospects buried in unread emails.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/Screenshot_2026-06-17_152756.png',
    pdf_url: 'https://res.cloudinary.com/dsyhgdfvc/raw/upload/v1781802000/portfolio/pdfs/real-estate-lead-qualification.pdf',
    live_url: 'https://ai-real-estate-lead-qualification.vercel.app/',
    tags: ['AI Agents', 'Real Estate', 'Lead Qualification', 'n8n'],
    tech_stack: ['n8n', 'Groq AI', 'Google Sheets', 'Email Automation', 'Lead Scoring'],
    duration: '1 week',
    metrics: [
      { value: '1–10', label: 'AI Lead Scoring', description: 'Intent-based qualification' },
      { value: '< 60s', label: 'Hot Lead Alert', description: 'Instant agent notification' },
      { value: '0', label: 'Manual Reviews', description: 'Fully automated triage' },
    ],
    content_blocks: [
      { type: 'lead', text: 'An intelligent lead qualification workflow that automatically scores buyer inquiries, prioritizes high-intent prospects, and delivers actionable insights to real estate agents in real time.' },

      { type: 'heading', level: 2, text: 'The Problem' },
      { type: 'paragraph', text: 'Real estate agents don\'t struggle to generate leads. They struggle to know which leads deserve immediate attention. Hours get burned reviewing messages and updating spreadsheets while motivated buyers sit unnoticed in a crowded inbox.' },
      { type: 'list', items: [
        'High-value opportunities get delayed responses',
        'Time wasted on low-intent inquiries',
        'Lead data fragmented across emails and spreadsheets',
        'Follow-up priorities unclear',
        'Deals lost to slow response times',
      ] },

      { type: 'heading', level: 2, text: 'The Objective' },
      { type: 'list', style: 'check', items: [
        'Identify serious buyers instantly',
        'Eliminate manual lead review',
        'Deliver real-time notifications for top prospects',
        'Centralize all lead information',
        'Create a structured workflow for follow-up',
      ] },

      { type: 'heading', level: 2, text: 'My Role' },
      { type: 'paragraph', text: 'Designed and built the end-to-end AI automation system: lead capture workflow (n8n), AI qualification engine (Groq), lead storage (Supabase / Google Sheets), notification system, and full architecture and scoring logic design.' },

      { type: 'heading', level: 2, text: 'The Solution' },
      { type: 'paragraph', text: 'An AI-driven lead qualification system that transforms unstructured buyer inquiries into a prioritized pipeline. Every submission is analyzed for intent, scored 1–10, and routed by urgency — so agents see a ranked list of prospects with clear next actions.' },

      { type: 'heading', level: 2, text: 'Workflow Overview' },

      { type: 'heading', level: 3, text: 'Step 1 — Lead Submission' },
      { type: 'paragraph', text: 'A buyer submits an inquiry through a capture form with name, email, phone, preferred location, budget, and message.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image.png', caption: 'Lead capture form' },

      { type: 'heading', level: 3, text: 'Step 2 — AI Qualification Engine' },
      { type: 'paragraph', text: 'The AI evaluates each inquiry against buying urgency, budget clarity, purchase readiness, engagement level, and overall intent — assigning a score between 1 and 10.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_1.png', caption: 'Qualification engine logic' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_2.png', caption: 'AI scoring output' },

      { type: 'heading', level: 3, text: 'Step 3 — Intelligent Lead Categorization' },
      { type: 'table',
        headers: ['Score', 'Classification', 'Recommended Action'],
        rows: [
          ['9–10', 'Hot Lead', 'Contact immediately'],
          ['7–8', 'High Priority', 'Follow up within 24 hours'],
          ['5–6', 'Nurture Lead', 'Keep engaged'],
          ['1–4', 'Low Intent', 'Archive for future campaigns'],
        ] },

      { type: 'heading', level: 3, text: 'Step 4 — Instant High-Value Lead Alerts' },
      { type: 'paragraph', text: 'When a Hot or High-Priority lead enters the system, an automated email fires immediately with lead info, AI-generated summary, qualification score, priority level, and suggested next action.' },
      { type: 'callout', tone: 'accent', title: 'Hot Lead Detected — Score 9.4/10', text: 'Buyer actively searching within stated budget. Recommend phone contact within 1 hour.' },

      { type: 'heading', level: 3, text: 'Step 5 — Automated Lead Database' },
      { type: 'paragraph', text: 'Every inquiry is automatically logged with contact info, budget, location, AI score, priority level, and timestamp — a centralized lead management system with zero manual data entry.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_3.png', caption: 'Auto-populated lead database' },

      { type: 'heading', level: 2, text: 'Business Impact' },
      { type: 'beforeAfter', before: [
        'Leads scattered across emails',
        'No qualification process',
        'Manual spreadsheet updates',
        'Unclear follow-up priorities',
        'High-value prospects easily overlooked',
      ], after: [
        'Every lead automatically scored',
        'High-intent buyers surfaced instantly',
        'Centralized lead tracking',
        'Faster response times',
        'More time closing deals, less time sorting inquiries',
      ] },

      { type: 'heading', level: 2, text: 'Project Gallery' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_4.png', caption: 'Workflow architecture' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_5.png', caption: 'Lead qualification dashboard' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_6.png', caption: 'Automated alert email' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/real-estate-lead-qualification/image_7.png', caption: 'Lead database' },

      { type: 'heading', level: 2, text: 'Outcome' },
      { type: 'paragraph', text: 'By automating qualification, prioritization, notifications, and record-keeping, agents spend less time managing inquiries and more time engaging with qualified buyers — focused on what generates revenue: meaningful conversations and closed deals.' },
    ],
    featured: false,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    project_id: null,
    title: 'PropIQ: AI System Qualifies Real Estate Leads & Books Consultations Automatically',
    slug: 'propiq-appointment-booking',
    client_name: 'PropIQ',
    client_industry: 'Real Estate',
    client_size: 'Independent agents & small agencies',
    challenge: 'Agents weren\'t losing deals from lack of leads — they were losing them because they couldn\'t respond fast enough. Between showings, negotiations, and client meetings, responding immediately to every inquiry was impossible. Manual scheduling, inconsistent follow-up, and poor lead prioritization created a deeply reactive sales process where deals fell through the cracks.',
    solution: 'Built PropIQ — a full-stack AI qualification and booking system. LLaMA 3.3 70B on Groq scores each lead 0–10, hot leads instantly receive a personalized response with a calendar booking link, AI-powered meeting briefs are generated before each consultation, and automated reminder sequences run for warm leads. Agents only engage with conversations that matter.',
    implementation: '6-stage pipeline: lead capture form → LLaMA 3.3 70B qualification (budget, intent, urgency, message quality) → smart routing (Hot 8–10, Warm 5–7, Cold 0–4) → instant agent notification with AI summary → Google Calendar self-booking → AI meeting brief generation. Next.js dashboard with Supabase backend tracks full pipeline visibility and conversion analytics.',
    results: 'Agents respond to every inquiry in under 60 seconds. Hot leads book consultations automatically without agent involvement. AI meeting briefs mean agents walk into every call fully prepared. System saves 2–3 hours per agent per day. Pipeline stays clean with automated status management. Agents can scale lead volume without adding headcount.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image.png',
    pdf_url: 'https://res.cloudinary.com/dsyhgdfvc/raw/upload/v1781802002/portfolio/pdfs/propiq-appointment-booking.pdf',
    live_url: 'https://propiq-ai-liart.vercel.app/',
    tags: ['AI Agents', 'Real Estate', 'Appointment Booking', 'PropIQ'],
    tech_stack: ['Groq (LLaMA 3.3 70B)', 'n8n', 'Supabase', 'Resend', 'Google Calendar', 'Next.js', 'TypeScript', 'Tailwind CSS'],
    duration: '2 weeks',
    metrics: [
      { value: '< 60s', label: 'Response Time', description: 'AI-powered instant replies' },
      { value: '2–3h', label: 'Saved Daily', description: 'Per agent, every day' },
      { value: 'Auto', label: 'Consultation Booking', description: 'No agent needed' },
    ],
    content_blocks: [
      { type: 'lead', text: 'Turn inbound property inquiries into qualified consultations — automatically. An AI-powered qualification and booking system that responds instantly, prioritizes high-intent buyers, automates follow-ups, and books consultations without manual intervention.' },

      { type: 'heading', level: 2, text: 'The Problem' },
      { type: 'paragraph', text: 'Most real estate agents don\'t lose deals from a lack of leads — they lose them because they respond too slowly. Buyers are significantly more likely to work with the first agent who replies, but agents are busy with showings, negotiations, and client meetings. As response times go up, conversion rates go down.' },

      { type: 'heading', level: 3, text: 'Typical Lead Workflow' },
      { type: 'list', items: [
        'Buyer submits an inquiry',
        'Agent receives notification',
        'Agent eventually reviews the inquiry',
        'Agent manually decides whether it\'s worth pursuing',
        'Agent sends an email',
        'Agent attempts to schedule a consultation',
        'Several follow-up messages are required',
        'Many leads disappear',
      ] },
      { type: 'paragraph', text: 'This creates three major problems: slow response times, inconsistent follow-up, and poor lead prioritization. As lead volume grows, the problems compound.' },

      { type: 'heading', level: 2, text: 'The Solution' },
      { type: 'paragraph', text: 'PropIQ acts as an intelligent layer between a lead form and an agent\'s calendar. Every lead receives immediate attention; agents focus only on conversations that matter.' },
      { type: 'list', style: 'check', items: [
        'Qualifies every lead using AI',
        'Scores buyer intent from 0–10',
        'Prioritizes high-value opportunities',
        'Sends personalized responses instantly',
        'Schedules consultations automatically',
        'Generates AI-powered meeting briefs',
        'Runs automated reminder sequences',
        'Maintains a clean sales pipeline',
      ] },

      { type: 'heading', level: 2, text: 'How It Works' },

      { type: 'heading', level: 3, text: 'Step 1 — Lead Submission' },
      { type: 'paragraph', text: 'A buyer submits a property inquiry through the website capturing name, email, location, property type, budget, and message.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_1.png', caption: 'Lead capture form' },

      { type: 'heading', level: 3, text: 'Step 2 — AI Qualification' },
      { type: 'paragraph', text: 'LLaMA 3.3 70B on Groq analyzes the inquiry against budget strength, purchase intent, urgency, message quality, and buying readiness — generating a 0–10 score.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_2.png', caption: 'AI qualification scoring' },

      { type: 'heading', level: 3, text: 'Step 3 — Lead Routing' },
      { type: 'paragraph', text: 'Hot leads (8–10) get a personalized email, a consultation booking link, and calendar scheduling options — all in under 60 seconds. Warm leads (5–7) enter an automated nurture sequence with agent visibility. Cold leads (0–4) are categorized and tracked without consuming agent time.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_3.png', caption: 'Hot lead routing & instant email' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_4.png', caption: 'Calendar scheduling experience' },

      { type: 'heading', level: 3, text: 'Step 4 — Agent Notification' },
      { type: 'paragraph', text: 'For qualified leads, the agent immediately receives lead details, qualification score, close probability, and a concise buyer summary — no manual review required.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_5.png', caption: 'Agent notification email' },

      { type: 'heading', level: 3, text: 'Step 5 — AI Meeting Brief Generation' },
      { type: 'paragraph', text: 'Before every consultation, PropIQ generates a prep brief with buyer goals, likely objections, recommended discovery questions, and key discussion points. Agents walk into every call prepared.' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_6.png', caption: 'AI-generated meeting brief' },

      { type: 'heading', level: 3, text: 'Step 6 — Automated Follow-Up' },
      { type: 'paragraph', text: 'If a consultation isn\'t booked, reminders fire at 24h and 48h. After 72h with no response, lead status is automatically updated to keep the pipeline clean.' },

      { type: 'heading', level: 2, text: 'Workflow Architecture' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_7.png', caption: 'End-to-end workflow orchestration' },
      { type: 'paragraph', text: 'The workflow orchestrates lead capture, AI qualification, database storage, email automation, calendar scheduling, reminder sequences, meeting brief generation, and analytics tracking — all running 24/7.' },

      { type: 'heading', level: 2, text: 'Dashboard' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_8.png', caption: 'PropIQ admin dashboard' },
      { type: 'paragraph', text: 'Lead pipeline visibility, lead scoring insights, appointment tracking, conversion monitoring, and funnel analytics — agents always know where their opportunities are.' },

      { type: 'heading', level: 2, text: 'Business Impact' },
      { type: 'table',
        headers: ['Process', 'Before PropIQ', 'After PropIQ'],
        rows: [
          ['Lead Qualification', 'Manual review', 'AI scoring'],
          ['Response Time', 'Hours', 'Under 60 seconds'],
          ['Follow-Up', 'Inconsistent', 'Automated'],
          ['Scheduling', 'Manual', 'Self-service'],
          ['Call Preparation', 'Minimal', 'AI briefs'],
          ['Pipeline Management', 'Time consuming', 'Automated'],
        ] },

      { type: 'heading', level: 2, text: 'Results' },
      { type: 'list', style: 'check', items: [
        'Respond instantly to every inquiry',
        'Capture high-intent buyers before competitors',
        'Save 2–3 hours per day per agent',
        'Eliminate forgotten follow-ups',
        'Improve consultation quality with AI briefs',
        'Maintain a cleaner sales pipeline',
        'Scale lead handling without hiring',
      ] },

      { type: 'heading', level: 2, text: 'Demo' },
      { type: 'image', url: 'https://res.cloudinary.com/dsyhgdfvc/image/upload/portfolio/case-studies/propiq-appointment-booking/image_9.png', caption: 'Workflow architecture in production' },

      { type: 'heading', level: 2, text: 'Conclusion' },
      { type: 'paragraph', text: 'PropIQ transforms a traditional lead form into a 24/7 AI sales assistant. Instead of manually reviewing inquiries, chasing prospects, and coordinating appointments, agents receive qualified opportunities ready for conversation — from lead capture to consultation booking, automatically.' },
    ],
    featured: true,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    author_name: 'Marcus Chen',
    author_role: 'Head of Sales',
    author_company: 'SaaS Platform',
    author_avatar_url: null,
    quote: 'Rifat built something I didn\'t think was possible — an AI that actually understands our ICP and writes emails that get replies. Our team loves it and the numbers speak for themselves.',
    rating: 5,
    project_id: '1',
    featured: true,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    author_name: 'Sarah Mitchell',
    author_role: 'CFO',
    author_company: 'Regional Logistics',
    author_avatar_url: null,
    quote: 'The ROI was obvious within the first month. What used to take my team a full week now runs overnight. Rifat\'s work paid for itself in under 30 days.',
    rating: 5,
    project_id: '2',
    featured: true,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    author_name: 'James Okafor',
    author_role: 'COO',
    author_company: 'DTC E-commerce Brand',
    author_avatar_url: null,
    quote: 'This dashboard is the single source of truth for our entire operation. We caught a fulfillment issue in 10 minutes that would have cost us $50K. Exceptional work.',
    rating: 5,
    project_id: '4',
    featured: true,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const processSteps = [
  {
    number: '01',
    title: 'Discovery',
    description: 'A 60-minute deep dive into your operations. We map your current workflows, identify the highest-leverage automation opportunities, and define clear success metrics.',
  },
  {
    number: '02',
    title: 'Architecture',
    description: 'I design the full system architecture — data flows, integration points, AI model selection, and fallback logic — before writing a single line of code.',
  },
  {
    number: '03',
    title: 'Build & Test',
    description: 'Iterative development with weekly demos. You see real progress, give feedback, and we ship in stages — reducing risk and getting you value faster.',
  },
  {
    number: '04',
    title: 'Launch & Optimize',
    description: 'Full deployment with monitoring, documentation, and a 30-day optimization period. I stay engaged until the system is performing at target metrics.',
  },
]
