import type { CaseStudy, Service, Testimonial, Project, HeroContent, Profile } from './types'

export const siteConfig = {
  name: 'Rifat Ahmed',
  title: 'AI Automation Consultant',
  description: 'I build AI systems and automation workflows that eliminate bottlenecks, reduce manual work, and unlock growth for ambitious businesses.',
  url: 'https://rifatahmed.dev',
  ogImage: '/og.png',
  email: 'hello@rifatahmed.dev',
  calendly: 'https://calendly.com/rifatahmed',
}

export const heroContent: HeroContent = {
  id: '1',
  headline: 'AI Systems That Save Time,\nReduce Costs &\nScale Operations.',
  subheadline: 'AI Automation Consultant & Builder',
  description: 'I build custom AI agents, workflow automations, CRM integrations and internal tools that eliminate repetitive work and help businesses operate faster.',
  cta_primary_text: 'Book A Discovery Call',
  cta_primary_href: '/contact',
  cta_secondary_text: 'View Case Studies',
  cta_secondary_href: '/case-studies',
  stat_1_value: '25+',
  stat_1_label: 'Automations Delivered',
  stat_2_value: '1,000+',
  stat_2_label: 'Hours Saved',
  stat_3_value: '15+',
  stat_3_label: 'Businesses Helped',
  stat_4_value: '80%',
  stat_4_label: 'Response Time Improvement',
  updated_at: new Date().toISOString(),
}

export const profile: Profile = {
  id: '1',
  name: 'Rifat Ahmed',
  title: 'AI Automation Consultant & Builder',
  bio: 'I help businesses move faster by replacing manual, repetitive work with intelligent automation systems built on AI agents, n8n, and custom tooling.',
  avatar_url: null,
  location: 'Remote · Worldwide',
  email: 'hello@rifatahmed.dev',
  phone: null,
  availability: 'Available for new projects',
  years_experience: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const services: Service[] = [
  {
    id: '1',
    title: 'AI Agents',
    description: 'Deploy AI that works around the clock — qualifying leads, responding to inquiries, and completing complex multi-step tasks without anyone lifting a finger.',
    icon: 'Bot',
    features: ['Multi-step reasoning', 'Tool use & API calls', 'Memory & context', 'Human-in-the-loop escalation'],
    sort_order: 1,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Workflow Automation',
    description: 'Connect every tool in your stack with trigger-based workflows that act instantly — eliminating manual handoffs and freeing your team from repetitive operational work.',
    icon: 'Workflow',
    features: ['400+ integrations', 'Custom logic nodes', 'Error handling & retries', 'Self-hosted or cloud'],
    sort_order: 2,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'CRM Integrations',
    description: 'Every lead, deal, and customer interaction synced in real time across HubSpot, Salesforce, or Pipedrive — so your team always has the full picture without data entry.',
    icon: 'Users',
    features: ['HubSpot, Salesforce, Pipedrive', 'Bi-directional sync', 'Custom field mapping', 'Event-driven triggers'],
    sort_order: 3,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Internal Business Tools',
    description: 'Replace scattered spreadsheets and one-off workarounds with purpose-built tools that give your entire team structure, shared visibility, and a single source of truth.',
    icon: 'Layers',
    features: ['Role-based access', 'Custom workflows', 'Data pipelines', 'API integrations'],
    sort_order: 4,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Dashboard Development',
    description: 'Pull data from every corner of your business into clean, real-time dashboards that give leadership instant visibility into performance, pipeline, and bottlenecks.',
    icon: 'BarChart3',
    features: ['Real-time data', 'Custom visualizations', 'Multi-source aggregation', 'Shareable reports'],
    sort_order: 5,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Lead Generation Systems',
    description: 'Automated pipelines that find, enrich, and qualify prospects 24/7 — delivering sales-ready leads directly into your CRM while your team stays focused on closing.',
    icon: 'Target',
    features: ['Multi-channel sourcing', 'AI enrichment', 'Intent scoring', 'Automated outreach'],
    sort_order: 6,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const caseStudies: CaseStudy[] = [
  {
    id: '1',
    project_id: null,
    title: 'AI Sales Agent Closes 3× More Deals for SaaS Company',
    slug: 'saas-ai-sales-agent',
    client_name: 'Confidential SaaS Co.',
    client_industry: 'B2B SaaS',
    client_size: '50–200 employees',
    challenge: 'The sales team was spending 4–6 hours daily on manual prospect research, follow-up emails, and CRM updates — leaving almost no time for actual selling. Pipeline visibility was poor and deals were slipping through the cracks.',
    solution: 'Built an AI sales agent using Claude + n8n that automatically researches inbound leads, scores them against ICP, drafts personalized outreach, and handles follow-up sequences — all synced in real time to HubSpot.',
    implementation: 'Deployed in 3 phases over 6 weeks: Phase 1 was lead enrichment and scoring, Phase 2 was automated outreach drafts with human review, Phase 3 was full autonomous follow-up with escalation triggers.',
    results: 'Sales team reclaimed 25+ hours per week. Qualified pipeline grew by 312% in 90 days. Deal velocity improved by 2.4×. Close rate increased from 18% to 31%.',
    testimonial_quote: 'Rifat built something I didn\'t think was possible — an AI that actually understands our ICP and writes emails that get replies. Our team loves it.',
    testimonial_author: 'Head of Sales',
    testimonial_role: 'Head of Sales',
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['AI Agents', 'n8n', 'HubSpot', 'Sales Automation'],
    tech_stack: ['Claude API', 'n8n', 'HubSpot', 'OpenAI', 'PostgreSQL'],
    duration: '6 weeks',
    metrics: [
      { value: '312%', label: 'Pipeline Growth', description: 'In first 90 days' },
      { value: '25h+', label: 'Weekly Time Saved', description: 'Per sales rep' },
      { value: '3×', label: 'Close Rate Improvement', description: '18% → 31%' },
    ],
    featured: true,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    project_id: null,
    title: 'Automated Invoice Processing Saves 40 Hours Weekly at Logistics Firm',
    slug: 'logistics-invoice-automation',
    client_name: 'Regional Logistics Co.',
    client_industry: 'Logistics & Supply Chain',
    client_size: '100–500 employees',
    challenge: 'Finance team manually processed 800+ invoices weekly across 40+ vendors — reconciling against POs, flagging discrepancies, and updating the ERP. Error rate was 4.2% and the process required 3 full-time staff.',
    solution: 'Built an intelligent document processing pipeline using OCR, Claude for extraction and validation, n8n for orchestration, and direct ERP API integration for automated posting.',
    implementation: null,
    results: 'Invoice processing time reduced from 45 minutes to under 2 minutes per invoice. Error rate dropped to 0.3%. 3 staff redeployed to higher-value work. Annual savings exceed $180,000.',
    testimonial_quote: 'The ROI was obvious within the first month. What used to take my team a full week now runs overnight.',
    testimonial_author: 'CFO',
    testimonial_role: 'CFO',
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['Document AI', 'n8n', 'ERP Integration', 'Finance Automation'],
    tech_stack: ['Claude API', 'n8n', 'OCR', 'REST APIs', 'PostgreSQL'],
    duration: '8 weeks',
    metrics: [
      { value: '96%', label: 'Time Reduction', description: '45 min → 2 min per invoice' },
      { value: '$180K', label: 'Annual Savings', description: 'Fully automated workflow' },
      { value: '0.3%', label: 'Error Rate', description: 'Down from 4.2%' },
    ],
    featured: true,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    project_id: null,
    title: 'Lead Generation System Delivers 500+ Qualified Leads Monthly for Agency',
    slug: 'agency-lead-generation-system',
    client_name: 'Growth Marketing Agency',
    client_industry: 'Digital Marketing',
    client_size: '10–50 employees',
    challenge: 'Agency relied entirely on referrals and had no systematic outbound. Founders were spending 15+ hours weekly manually finding leads, most of which didn\'t convert because targeting was imprecise.',
    solution: 'Built a multi-channel lead generation system that scrapes, enriches, scores, and sequences prospects from LinkedIn, Apollo, and industry databases — with AI-generated personalization at scale.',
    implementation: null,
    results: '500+ qualified leads per month on autopilot. 22% email open rate (industry average: 21%). 8% reply rate (industry average: 3%). 4 new clients signed in first month.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['Lead Generation', 'AI Personalization', 'n8n', 'LinkedIn'],
    tech_stack: ['n8n', 'Claude API', 'Apollo API', 'LinkedIn', 'Instantly'],
    duration: '4 weeks',
    metrics: [
      { value: '500+', label: 'Leads/Month', description: 'Fully automated pipeline' },
      { value: '8%', label: 'Reply Rate', description: '2.7× industry average' },
      { value: '4', label: 'New Clients', description: 'In first 30 days' },
    ],
    featured: true,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    project_id: null,
    title: 'Real-Time Operations Dashboard Unifies 7 Data Sources for E-commerce Brand',
    slug: 'ecommerce-operations-dashboard',
    client_name: 'DTC E-commerce Brand',
    client_industry: 'E-commerce',
    client_size: '$5M–$20M ARR',
    challenge: 'Leadership team was making decisions based on day-old reports manually compiled from Shopify, Meta Ads, Google Ads, Klaviyo, Warehouse WMS, and 3PL — a 3-hour daily exercise with no real-time visibility.',
    solution: 'Built a unified operations dashboard with real-time data pipelines from all 7 sources, with automated anomaly detection and Slack alerts for key threshold breaches.',
    implementation: null,
    results: 'Decision latency reduced from 24 hours to 5 minutes. Ad spend optimization improved ROAS by 34% in 60 days. Daily report preparation eliminated (saving 15 hours/week for ops team).',
    testimonial_quote: 'This dashboard is the single source of truth for our entire operation. We caught a fulfillment issue in 10 minutes that would have cost us $50K.',
    testimonial_author: 'COO',
    testimonial_role: 'COO',
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['Dashboard', 'Data Integration', 'n8n', 'Real-Time Analytics'],
    tech_stack: ['Next.js', 'Supabase', 'n8n', 'Shopify API', 'Meta API'],
    duration: '5 weeks',
    metrics: [
      { value: '34%', label: 'ROAS Improvement', description: 'Within 60 days' },
      { value: '15h', label: 'Saved Weekly', description: 'Report automation' },
      { value: '5 min', label: 'Decision Latency', description: 'Down from 24 hours' },
    ],
    featured: false,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    project_id: null,
    title: 'AI Lead Response System Cuts Real Estate Reply Time from Hours to 30 Seconds',
    slug: 'real-estate-lead-response',
    client_name: 'Real Estate Agency',
    client_industry: 'Real Estate',
    client_size: 'Small agency',
    challenge: 'A growing real estate agency was losing qualified buyers due to slow response times. New inquiries sat unanswered for hours, leads arriving outside business hours went completely unaddressed, and agents spent significant time writing repetitive follow-up emails — resulting in lost opportunities before any real conversation began.',
    solution: 'Built an AI-powered Lead Response System that instantly captures buyer inquiries, generates personalized email responses within 30 seconds using AI, assigns a lead quality score, logs every submission to a centralized database, and automatically runs a multi-step nurture sequence on Day 2, Day 5, and Day 7.',
    implementation: 'Deployed in 3 phases over 1 week: Phase 1 — AI response generation with a 30-second reply SLA. Phase 2 — Lead scoring and qualification logic to surface high-intent buyers. Phase 3 — Automated multi-step follow-up sequences operating 24/7, including weekends and holidays.',
    results: 'Every inquiry now receives a personalized AI response within 30 seconds, including evenings and weekends. Agents were freed from writing repetitive replies. Lead data centralized in a searchable database. Zero missed inquiries outside business hours. Buyer engagement improved across the entire funnel.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['AI Agents', 'Real Estate', 'Lead Automation', 'Email Automation'],
    tech_stack: ['n8n', 'Claude API', 'Email Automation', 'Google Sheets', 'Lead Scoring'],
    duration: '1 week',
    metrics: [
      { value: '30s', label: 'Response Time', description: 'Down from hours of delay' },
      { value: '24/7', label: 'Availability', description: 'Including evenings & weekends' },
      { value: '3-Step', label: 'Follow-Up Sequence', description: 'Day 2, Day 5, Day 7' },
    ],
    featured: false,
    sort_order: 5,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    project_id: null,
    title: 'AI Lead Qualification System Surfaces High-Intent Buyers Instantly for Real Estate Agency',
    slug: 'real-estate-lead-qualification',
    client_name: 'Real Estate Agency',
    client_industry: 'Real Estate',
    client_size: 'Small–mid agency',
    challenge: 'Agents were receiving a constant stream of inquiries from websites, landing pages, and property portals but had no system to separate serious buyers from tire-kickers. Hours were wasted manually reviewing low-intent leads while high-value prospects waited in a crowded inbox — creating a reactive, inefficient sales process.',
    solution: 'Built an AI-driven Lead Qualification System using Groq AI that evaluates each inquiry against buying urgency, budget clarity, and purchase readiness. Each lead is scored 1–10 and routed into Hot / High Priority / Nurture / Low Intent categories. Instant email alerts fire for Hot and High Priority leads with AI-generated summaries and recommended next actions.',
    implementation: 'Single automated pipeline: inquiry submission → Groq AI evaluation (buying intent, budget, urgency, message quality) → score assignment (1–10) → category routing → instant email alert for top leads → auto-log to Google Sheets. Hot leads (9–10) trigger an agent notification within 60 seconds.',
    results: 'Every lead automatically scored within seconds of submission. High-intent buyers now surface to agents immediately. Centralized Google Sheets database eliminated manual data entry. Agents focus 100% of follow-up energy on leads most likely to close. No more missed hot prospects buried in unread emails.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: null,
    pdf_url: null,
    live_url: null,
    tags: ['AI Agents', 'Real Estate', 'Lead Qualification', 'n8n'],
    tech_stack: ['n8n', 'Groq AI', 'Google Sheets', 'Email Automation', 'Lead Scoring'],
    duration: '1 week',
    metrics: [
      { value: '1–10', label: 'AI Lead Scoring', description: 'Intent-based qualification' },
      { value: '< 60s', label: 'Hot Lead Alert', description: 'Instant agent notification' },
      { value: '0', label: 'Manual Reviews', description: 'Fully automated triage' },
    ],
    featured: false,
    sort_order: 6,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    project_id: null,
    title: 'PropIQ: AI System Qualifies Real Estate Leads & Books Consultations Automatically',
    slug: 'propiq-appointment-booking',
    client_name: 'PropIQ',
    client_industry: 'Real Estate',
    client_size: 'Independent agents & small agencies',
    challenge: 'Agents weren\'t losing deals from lack of leads — they were losing them because they couldn\'t respond fast enough. Between showings, negotiations, and client meetings, responding immediately to every inquiry was impossible. Manual scheduling, inconsistent follow-up, and poor lead prioritization created a deeply reactive sales process where deals fell through the cracks.',
    solution: 'Built PropIQ — a full-stack AI qualification and booking system. LLaMA 3.3 70B on Groq scores each lead 0–10, hot leads instantly receive a personalized response with a calendar booking link, AI-powered meeting briefs are generated before each consultation, and automated reminder sequences run for warm leads. Agents only engage with conversations that matter.',
    implementation: '6-stage pipeline: lead capture form → LLaMA 3.3 70B qualification (budget, intent, urgency, message quality) → smart routing (Hot 8–10, Warm 5–7, Cold 0–4) → instant agent notification with AI summary → Google Calendar self-booking → AI meeting brief generation. Next.js dashboard with Supabase backend tracks full pipeline visibility and conversion analytics.',
    results: 'Agents respond to every inquiry in under 60 seconds. Hot leads book consultations automatically without agent involvement. AI meeting briefs mean agents walk into every call fully prepared. System saves 2–3 hours per agent per day. Pipeline stays clean with automated status management. Agents can scale lead volume without adding headcount.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: null,
    pdf_url: null,
    live_url: 'https://propiq-ai-liart.vercel.app/',
    tags: ['AI Agents', 'Real Estate', 'Appointment Booking', 'PropIQ'],
    tech_stack: ['Groq (LLaMA 3.3 70B)', 'n8n', 'Supabase', 'Resend', 'Google Calendar', 'Next.js', 'TypeScript', 'Tailwind CSS'],
    duration: '2 weeks',
    metrics: [
      { value: '< 60s', label: 'Response Time', description: 'AI-powered instant replies' },
      { value: '2–3h', label: 'Saved Daily', description: 'Per agent, every day' },
      { value: 'Auto', label: 'Consultation Booking', description: 'No agent needed' },
    ],
    featured: true,
    sort_order: 7,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    author_name: 'Marcus Chen',
    author_role: 'Head of Sales',
    author_company: 'SaaS Platform',
    author_avatar_url: null,
    quote: 'Rifat built something I didn\'t think was possible — an AI that actually understands our ICP and writes emails that get replies. Our team loves it and the numbers speak for themselves.',
    rating: 5,
    project_id: '1',
    featured: true,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    author_name: 'Sarah Mitchell',
    author_role: 'CFO',
    author_company: 'Regional Logistics',
    author_avatar_url: null,
    quote: 'The ROI was obvious within the first month. What used to take my team a full week now runs overnight. Rifat\'s work paid for itself in under 30 days.',
    rating: 5,
    project_id: '2',
    featured: true,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    author_name: 'James Okafor',
    author_role: 'COO',
    author_company: 'DTC E-commerce Brand',
    author_avatar_url: null,
    quote: 'This dashboard is the single source of truth for our entire operation. We caught a fulfillment issue in 10 minutes that would have cost us $50K. Exceptional work.',
    rating: 5,
    project_id: '4',
    featured: true,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const processSteps = [
  {
    number: '01',
    title: 'Discovery',
    description: 'A 60-minute deep dive into your operations. We map your current workflows, identify the highest-leverage automation opportunities, and define clear success metrics.',
  },
  {
    number: '02',
    title: 'Architecture',
    description: 'I design the full system architecture — data flows, integration points, AI model selection, and fallback logic — before writing a single line of code.',
  },
  {
    number: '03',
    title: 'Build & Test',
    description: 'Iterative development with weekly demos. You see real progress, give feedback, and we ship in stages — reducing risk and getting you value faster.',
  },
  {
    number: '04',
    title: 'Launch & Optimize',
    description: 'Full deployment with monitoring, documentation, and a 30-day optimization period. I stay engaged until the system is performing at target metrics.',
  },
]
