import type { CaseStudy, Service, Testimonial, Project, HeroContent, Profile } from './types'

export const siteConfig = {
  name: 'Rifat Ahmed',
  title: 'AI Automation Consultant',
  description: 'I build AI systems and automation workflows that eliminate bottlenecks, reduce manual work, and unlock growth for ambitious businesses.',
  url: 'https://rifatahmed.dev',
  ogImage: '/og.png',
  email: 'hello@rifatahmed.dev',
  calendly: 'https://calendly.com/rifatahmed',
}

export const heroContent: HeroContent = {
  id: '1',
  headline: 'AI Systems That Save Time,\nReduce Costs &\nScale Operations.',
  subheadline: 'AI Automation Consultant & Builder',
  description: 'I build custom AI agents, workflow automations, CRM integrations and internal tools that eliminate repetitive work and help businesses operate faster.',
  cta_primary_text: 'Book A Discovery Call',
  cta_primary_href: '/contact',
  cta_secondary_text: 'View Case Studies',
  cta_secondary_href: '/case-studies',
  stat_1_value: '25+',
  stat_1_label: 'Automations Delivered',
  stat_2_value: '1,000+',
  stat_2_label: 'Hours Saved',
  stat_3_value: '15+',
  stat_3_label: 'Businesses Helped',
  stat_4_value: '80%',
  stat_4_label: 'Response Time Improvement',
  updated_at: new Date().toISOString(),
}

export const profile: Profile = {
  id: '1',
  name: 'Rifat Ahmed',
  title: 'AI Automation Consultant & Builder',
  bio: 'I help businesses move faster by replacing manual, repetitive work with intelligent automation systems built on AI agents, n8n, and custom tooling.',
  avatar_url: null,
  location: 'Remote · Worldwide',
  email: 'hello@rifatahmed.dev',
  phone: null,
  availability: 'Available for new projects',
  years_experience: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const services: Service[] = [
  {
    id: '1',
    title: 'AI Agents',
    description: 'Deploy AI that works around the clock — qualifying leads, responding to inquiries, and completing complex multi-step tasks without anyone lifting a finger.',
    icon: 'Bot',
    features: ['Multi-step reasoning', 'Tool use & API calls', 'Memory & context', 'Human-in-the-loop escalation'],
    sort_order: 1,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Workflow Automation',
    description: 'Connect every tool in your stack with trigger-based workflows that act instantly — eliminating manual handoffs and freeing your team from repetitive operational work.',
    icon: 'Workflow',
    features: ['400+ integrations', 'Custom logic nodes', 'Error handling & retries', 'Self-hosted or cloud'],
    sort_order: 2,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'CRM Integrations',
    description: 'Every lead, deal, and customer interaction synced in real time across HubSpot, Salesforce, or Pipedrive — so your team always has the full picture without data entry.',
    icon: 'Users',
    features: ['HubSpot, Salesforce, Pipedrive', 'Bi-directional sync', 'Custom field mapping', 'Event-driven triggers'],
    sort_order: 3,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Internal Business Tools',
    description: 'Replace scattered spreadsheets and one-off workarounds with purpose-built tools that give your entire team structure, shared visibility, and a single source of truth.',
    icon: 'Layers',
    features: ['Role-based access', 'Custom workflows', 'Data pipelines', 'API integrations'],
    sort_order: 4,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Dashboard Development',
    description: 'Pull data from every corner of your business into clean, real-time dashboards that give leadership instant visibility into performance, pipeline, and bottlenecks.',
    icon: 'BarChart3',
    features: ['Real-time data', 'Custom visualizations', 'Multi-source aggregation', 'Shareable reports'],
    sort_order: 5,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Lead Generation Systems',
    description: 'Automated pipelines that find, enrich, and qualify prospects 24/7 — delivering sales-ready leads directly into your CRM while your team stays focused on closing.',
    icon: 'Target',
    features: ['Multi-channel sourcing', 'AI enrichment', 'Intent scoring', 'Automated outreach'],
    sort_order: 6,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const caseStudies: CaseStudy[] = [
  {
    id: '1',
    project_id: null,
    title: 'AI Sales Agent Closes 3× More Deals for SaaS Company',
    slug: 'saas-ai-sales-agent',
    client_name: 'Confidential SaaS Co.',
    client_industry: 'B2B SaaS',
    client_size: '50–200 employees',
    challenge: 'The sales team was spending 4–6 hours daily on manual prospect research, follow-up emails, and CRM updates — leaving almost no time for actual selling. Pipeline visibility was poor and deals were slipping through the cracks.',
    solution: 'Built an AI sales agent using Claude + n8n that automatically researches inbound leads, scores them against ICP, drafts personalized outreach, and handles follow-up sequences — all synced in real time to HubSpot.',
    implementation: 'Deployed in 3 phases over 6 weeks: Phase 1 was lead enrichment and scoring, Phase 2 was automated outreach drafts with human review, Phase 3 was full autonomous follow-up with escalation triggers.',
    results: 'Sales team reclaimed 25+ hours per week. Qualified pipeline grew by 312% in 90 days. Deal velocity improved by 2.4×. Close rate increased from 18% to 31%.',
    testimonial_quote: 'Rifat built something I didn\'t think was possible — an AI that actually understands our ICP and writes emails that get replies. Our team loves it.',
    testimonial_author: 'Head of Sales',
    testimonial_role: 'Head of Sales',
    cover_image_url: null,
    tags: ['AI Agents', 'n8n', 'HubSpot', 'Sales Automation'],
    tech_stack: ['Claude API', 'n8n', 'HubSpot', 'OpenAI', 'PostgreSQL'],
    duration: '6 weeks',
    metrics: [
      { value: '312%', label: 'Pipeline Growth', description: 'In first 90 days' },
      { value: '25h+', label: 'Weekly Time Saved', description: 'Per sales rep' },
      { value: '3×', label: 'Close Rate Improvement', description: '18% → 31%' },
    ],
    featured: true,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    project_id: null,
    title: 'Automated Invoice Processing Saves 40 Hours Weekly at Logistics Firm',
    slug: 'logistics-invoice-automation',
    client_name: 'Regional Logistics Co.',
    client_industry: 'Logistics & Supply Chain',
    client_size: '100–500 employees',
    challenge: 'Finance team manually processed 800+ invoices weekly across 40+ vendors — reconciling against POs, flagging discrepancies, and updating the ERP. Error rate was 4.2% and the process required 3 full-time staff.',
    solution: 'Built an intelligent document processing pipeline using OCR, Claude for extraction and validation, n8n for orchestration, and direct ERP API integration for automated posting.',
    implementation: null,
    results: 'Invoice processing time reduced from 45 minutes to under 2 minutes per invoice. Error rate dropped to 0.3%. 3 staff redeployed to higher-value work. Annual savings exceed $180,000.',
    testimonial_quote: 'The ROI was obvious within the first month. What used to take my team a full week now runs overnight.',
    testimonial_author: 'CFO',
    testimonial_role: 'CFO',
    cover_image_url: null,
    tags: ['Document AI', 'n8n', 'ERP Integration', 'Finance Automation'],
    tech_stack: ['Claude API', 'n8n', 'OCR', 'REST APIs', 'PostgreSQL'],
    duration: '8 weeks',
    metrics: [
      { value: '96%', label: 'Time Reduction', description: '45 min → 2 min per invoice' },
      { value: '$180K', label: 'Annual Savings', description: 'Fully automated workflow' },
      { value: '0.3%', label: 'Error Rate', description: 'Down from 4.2%' },
    ],
    featured: true,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    project_id: null,
    title: 'Lead Generation System Delivers 500+ Qualified Leads Monthly for Agency',
    slug: 'agency-lead-generation-system',
    client_name: 'Growth Marketing Agency',
    client_industry: 'Digital Marketing',
    client_size: '10–50 employees',
    challenge: 'Agency relied entirely on referrals and had no systematic outbound. Founders were spending 15+ hours weekly manually finding leads, most of which didn\'t convert because targeting was imprecise.',
    solution: 'Built a multi-channel lead generation system that scrapes, enriches, scores, and sequences prospects from LinkedIn, Apollo, and industry databases — with AI-generated personalization at scale.',
    implementation: null,
    results: '500+ qualified leads per month on autopilot. 22% email open rate (industry average: 21%). 8% reply rate (industry average: 3%). 4 new clients signed in first month.',
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    cover_image_url: null,
    tags: ['Lead Generation', 'AI Personalization', 'n8n', 'LinkedIn'],
    tech_stack: ['n8n', 'Claude API', 'Apollo API', 'LinkedIn', 'Instantly'],
    duration: '4 weeks',
    metrics: [
      { value: '500+', label: 'Leads/Month', description: 'Fully automated pipeline' },
      { value: '8%', label: 'Reply Rate', description: '2.7× industry average' },
      { value: '4', label: 'New Clients', description: 'In first 30 days' },
    ],
    featured: true,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    project_id: null,
    title: 'Real-Time Operations Dashboard Unifies 7 Data Sources for E-commerce Brand',
    slug: 'ecommerce-operations-dashboard',
    client_name: 'DTC E-commerce Brand',
    client_industry: 'E-commerce',
    client_size: '$5M–$20M ARR',
    challenge: 'Leadership team was making decisions based on day-old reports manually compiled from Shopify, Meta Ads, Google Ads, Klaviyo, Warehouse WMS, and 3PL — a 3-hour daily exercise with no real-time visibility.',
    solution: 'Built a unified operations dashboard with real-time data pipelines from all 7 sources, with automated anomaly detection and Slack alerts for key threshold breaches.',
    implementation: null,
    results: 'Decision latency reduced from 24 hours to 5 minutes. Ad spend optimization improved ROAS by 34% in 60 days. Daily report preparation eliminated (saving 15 hours/week for ops team).',
    testimonial_quote: 'This dashboard is the single source of truth for our entire operation. We caught a fulfillment issue in 10 minutes that would have cost us $50K.',
    testimonial_author: 'COO',
    testimonial_role: 'COO',
    cover_image_url: null,
    tags: ['Dashboard', 'Data Integration', 'n8n', 'Real-Time Analytics'],
    tech_stack: ['Next.js', 'Supabase', 'n8n', 'Shopify API', 'Meta API'],
    duration: '5 weeks',
    metrics: [
      { value: '34%', label: 'ROAS Improvement', description: 'Within 60 days' },
      { value: '15h', label: 'Saved Weekly', description: 'Report automation' },
      { value: '5 min', label: 'Decision Latency', description: 'Down from 24 hours' },
    ],
    featured: false,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    author_name: 'Marcus Chen',
    author_role: 'Head of Sales',
    author_company: 'SaaS Platform',
    author_avatar_url: null,
    quote: 'Rifat built something I didn\'t think was possible — an AI that actually understands our ICP and writes emails that get replies. Our team loves it and the numbers speak for themselves.',
    rating: 5,
    project_id: '1',
    featured: true,
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    author_name: 'Sarah Mitchell',
    author_role: 'CFO',
    author_company: 'Regional Logistics',
    author_avatar_url: null,
    quote: 'The ROI was obvious within the first month. What used to take my team a full week now runs overnight. Rifat\'s work paid for itself in under 30 days.',
    rating: 5,
    project_id: '2',
    featured: true,
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    author_name: 'James Okafor',
    author_role: 'COO',
    author_company: 'DTC E-commerce Brand',
    author_avatar_url: null,
    quote: 'This dashboard is the single source of truth for our entire operation. We caught a fulfillment issue in 10 minutes that would have cost us $50K. Exceptional work.',
    rating: 5,
    project_id: '4',
    featured: true,
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const processSteps = [
  {
    number: '01',
    title: 'Discovery',
    description: 'A 60-minute deep dive into your operations. We map your current workflows, identify the highest-leverage automation opportunities, and define clear success metrics.',
  },
  {
    number: '02',
    title: 'Architecture',
    description: 'I design the full system architecture — data flows, integration points, AI model selection, and fallback logic — before writing a single line of code.',
  },
  {
    number: '03',
    title: 'Build & Test',
    description: 'Iterative development with weekly demos. You see real progress, give feedback, and we ship in stages — reducing risk and getting you value faster.',
  },
  {
    number: '04',
    title: 'Launch & Optimize',
    description: 'Full deployment with monitoring, documentation, and a 30-day optimization period. I stay engaged until the system is performing at target metrics.',
  },
]
